apiVersion: v1
appVersion: "0.0.0"  # replace with actual version during release process
version: 0.0.0 # replace with actual version during release process
description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge via Netcup
name: cert-manager-webhook-netcup
home: https://github.com/aellwein/cert-manager-webhook-netcup
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - netcup
  - ACME
  - DNS01
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Alex Ellwein
      email: alex.ellwein@gmail.com
  artifacthub.io/containsSecurityUpdates: "false"
  # kinds: added, changed, deprecated, removed, fixed, security.
  artifacthub.io/changes: |
    - kind: added
      description: "Added OCI chart deployment with chart signing"
    - kind: changed
      description: "Bump indirect dependencies"
  artifacthub.io/signKey: |
    fingerprint: "FA1F0CE58313D2638809BD05D51650A7D1BE5944"
    url: https://gist.githubusercontent.com/aellwein/112e7c157c4f60165b62602b2b62c2d7/raw/491cc2925f43ddb015d63c95f5ea2bca1f281c8c/pubkey.asc
