name: Build Image (branch:develop - linux/arm64)
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_image:
    uses: ./.github/workflows/build_image_for_arch.yml
    with:
    secrets: inherit
      branch: develop
      platform: linux/arm64
      image_tag: develop