name: build image

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      platform:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      deploy_oci_chart:
        required: false
        type: boolean
        default: false
      chart_version:
        required: false
        type: string
        default: "0.0.0-dev"

env:
  KO_DOCKER_REPO: ghcr.io/aellwein

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Setup ko
        uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9.0

      - name: Set tag output
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

      - name: run ko build
        id: ko-build
        env:
          auth_token: ${{ github.token }}
        run: |
          echo "${auth_token}" | ko login ghcr.io -u aellwein --password-stdin && \
          VERSION=${{ inputs.image_tag }} KO_DEFAULTBASEIMAGE=gcr.io/distroless/static-debian12 ko build -B -t ${{ inputs.image_tag }}  --platform=${{ inputs.platform }}
          docker pull ${KO_DOCKER_REPO}/cert-manager-webhook-netcup:${{ inputs.image_tag }}
          docker inspect --format='{{index .RepoDigests 0}}' ${KO_DOCKER_REPO}/cert-manager-webhook-netcup:${{ inputs.image_tag }} | sed -e 's/.*@//' > image_digest.txt
          DIGEST=$(cat image_digest.txt)
          echo "image_digest=${DIGEST}" >> "$GITHUB_OUTPUT"
          echo "Image digest: ${DIGEST}"

      - name: Prepare Helm chart
        if: ${{ inputs.deploy_oci_chart && success() }}
        run: |
          yq e -i ".appVersion = \"${{ inputs.chart_version }}\"" deploy/cert-manager-webhook-netcup/Chart.yaml
          yq e -i ".version = \"${{ inputs.chart_version }}\"" deploy/cert-manager-webhook-netcup/Chart.yaml
          yq -e -i ".image.hash = \"${{ steps.ko-build.outputs.image_digest }}\"" deploy/cert-manager-webhook-netcup/values.yaml

      - name: Import GPG key
        if: ${{ inputs.deploy_oci_chart && success() }}
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        id: gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Helm requires the legacy GPG format
      # @link https://helm.sh/docs/topics/provenance/#the-workflow
      - name: Convert GPG v2 key
        if: ${{ inputs.deploy_oci_chart && success() }}
        run: |
          gpg --export > ~/.gnupg/pubring.gpg
          gpg --batch --pinentry-mode loopback --yes --passphrase '${{ secrets.GPG_PASSPHRASE }}' --export-secret-key > ~/.gnupg/secring.gpg


      - name: Push and sign OCI chart
        if: ${{ inputs.deploy_oci_chart && success() }}
        uses: appany/helm-oci-chart-releaser@d94988c92bed2e09c6113981f15f8bb495d10943 # v0.5.0
        with:
          name: cert-manager-webhook-netcup
          registry: ghcr.io
          repository: aellwein/cert-manager-webhook-netcup
          tag: ${{ inputs.chart_version }}
          path: deploy/cert-manager-webhook-netcup
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          sign: true
          signing_key: ${{ steps.gpg.outputs.name }}
          signing_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          update_dependencies: 'true'
